[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "selveri"
version = "0.9.0"
authors = [
    { name = "Yağız Kaan Aydoğdu", email = "y.kaan.aydogdu@gmail.com" },
    { name = "Yusuf Demir", email = "yusufdemir12610@gmail.com" },
]
description = "SelVeri: Self-Verifying Programming Language"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "lark",
    "ltlf2dfa",
    "z3-solver",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: Microsoft :: Windows",
]

[project.scripts]
selveri = "selveri.cli:main"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[project.urls]
Homepage = "https://github.com/Selveri-Corp/selveri"
Issues = "https://github.com/Selveri-Corp/selveri/issues"
